kind: pipeline
name: default
steps:
  - name: build
    image: node:latest
    commands: 
      - mkdir dist
      - npm i
      - npm run lint
      - npm install --global webpack-cli webpack
      - webpack
      - mv stories dist/
      - mv package.json dist/
      - tar cvzf dist.tar.gz dist/
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: server_host
      username:
        from_secret: server_user
      key:
        from_secret: ssh_key
      port: 22
      target: /home/runner/bots/storybot
      source: dist.tar.gz
  - name: run commands
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: server_host
      username:
        from_secret: server_user
      key:
        from_secret: ssh_key
      port: 22
      script:
        - bash /home/runner/bots/storybot/deploy.sh