version: 2
jobs:
  build:
    docker:
      - image: node:12.13.1-stretch-slim
    working_directory: ~/app
    branches:
      only:
        - main
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b5:bb:a7:23:11:5e:64:89:ba:89:cd:9a:c2:ac:b0:e9"
      - run:
          name: Check node version
          command: |
            node -v
      - run:
          name: Install packages 
          command: |
            DEBIAN_FRONTEND=noninteractive apt update -y
            apt install openssh-client -y
      - run:
          name: install npm packages
          command: |
            npm i
            npm install --global webpack-cli webpack
      - run:
          name: build
          command: |
            webpack
            mv stories dist/
            mv package.json dist/
            tar cvzf dist.tar.gz dist/
            ssh-keygen -F $SERVER >/dev/null || ssh-keyscan -H $SERVER >> ~/.ssh/known_hosts
      - run:
          name: Transfer tar
          command: |
            scp -i ~/.ssh/id_rsa* dist.tar.gz $USER@$SERVER:~/bots/$APPNAME
      - run:
          name: Deploy
          command: |
            ssh -t $USER@$SERVER "bash /home/$USER/bots/$APPNAME/deploy.sh"
            